version: '3'

services:
  usagemeterbackend:
    image: usagemeterbackend
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    env_file: ./api.env

  userservice:
    image: userservice 
    build: 
      context: user-service/
      dockerfile: Dockerfile
    network_mode: "host"
    volumes: 
      - /home/sachith/Documents/Projects/Office/files:/files
    env_file: ./api.env

  adminservice:
    image: adminmodule 
    build: 
      context: admin-module/
      dockerfile: Dockerfile
    network_mode: "host"
    env_file: ./api.env
  
  notificationservice:
    image: notificationservice
    build: 
      context: notification-service/
      dockerfile: Dockerfile
    network_mode: "host"
    env_file: ./api.env