version: '3'

services:
  mysqlserver:
    image: mysql-server
    container_name: mysqlcontainer
    build:
      context: mysql-module/
      dockerfile: Dockerfile
    env_file: mysql-module/mysql.env
    networks: 
      - backend
    volumes: 
      - ./mysql-data:/var/lib/mysql
    ports: 
      - 8001:3306

  usagemeterbackend:
    image: usagemeterbackend
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 7171:7171
    env_file: ./api.env
    networks: 
      - backend

  userservice:
    image: userservice 
    build: 
      context: user-service/
      dockerfile: Dockerfile
    networks: 
      - backend
    volumes: 
      - /home/sachith/Documents/Projects/Office/files:/files
    env_file: ./api.env
    networks: 
      - backend

  adminservice:
    image: adminmodule 
    build: 
      context: admin-module/
      dockerfile: Dockerfile
    networks: 
      - backend
    env_file: ./api.env
    networks: 
      - backend
  
  notificationservice:
    image: notificationservice
    build: 
      context: notification-service/
      dockerfile: Dockerfile
    networks: 
      - backend
    env_file: ./api.env
    networks: 
      - backend
  
  loadbalancer:
    image: nginx
    build: 
        context: ./nginx
        dockerfile: Dockerfile
    ports: 
    - 9090:80
    networks: 
      - backend

networks: 
  backend:
    driver: "bridge"