version: '3'

services:
  usagemeterbackend:
    image: usagemeterbackend
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"

  user-service:
    image: user-service 
    build: 
      context: user-service/
      dockerfile: Dockerfile
    network_mode: "host"