version: '3'

services:
  usagemeterbackend:
    image: usagemeterbackend
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    env_file: ./api.env

  userservice:
    image: userservice 
    build: 
      context: user-service/
      dockerfile: Dockerfile
    network_mode: "host"
    env_file: ./api.env